### ISSUE TITLE
Increase font weight for unread channels

### ISSUE THREAD

**Issue by chasegiunta** [dennisfrank/decent-discord#10]
To distinguish between unread/read & active channel, as Slack does.
![image](https://user-images.githubusercontent.com/1377169/53036244-f8e5c280-343c-11e9-909c-68fe946a7c57.png)

**Comment by dennisfrank** [comment]
@chasegiunta Would this be okay? 5145ce69a07917d9f5e8d856c1ec41e29a9611cb
<img width="189" alt="image" src="https://user-images.githubusercontent.com/65968/53290336-c3c1d300-37a2-11e9-8dd7-6900d7db4a37.png">
