### ISSUE TITLE
Invert active channel

### ISSUE THREAD

**Issue by chasegiunta** [dennisfrank/decent-discord#11]
Slack does a good job of highlighting which channel you're looking at, to reduce confusion. Maybe the active channel should be inverted?

![image](https://user-images.githubusercontent.com/1377169/53036553-950fc980-343d-11e9-9437-acd252ea397b.png)

![image](https://user-images.githubusercontent.com/1377169/53036648-cab4b280-343d-11e9-8306-2dd17bf5f581.png)

**Comment by dennisfrank** [comment]
@chasegiunta This is how it looks with the latest release:

<img width="213" alt="image" src="https://user-images.githubusercontent.com/65968/53290554-fae5b380-37a5-11e9-88e9-a197d470c34f.png">

5145ce69a07917d9f5e8d856c1ec41e29a9611cb
