### ISSUE TITLE
Highlighted only a single message at a time

### ISSUE THREAD

**Issue by lindseydiloreto** [dennisfrank/decent-discord#19]
When you hover over a message, the background turns grey (like Slack). I love that! ❤️ 

But it seems to highlight _all_ messages in that block from that user. So if the person posted 3 times in a row, all 3 messages will be highlighted.

Is there a way to restrict that to a single message? It makes it a little trickier to find the reaction/edit links when you hover over on the right-hand side.

**Comment by jalendport** [comment]
Was already planning on taking a look at this when I get around to #16 (hopefully this week) 👍

**Comment by lindseydiloreto** [comment]
Brilliant, thanks @jalendport! Upvoted that issue as well 👍

**Comment by jalendport** [comment]
@lindseydiloreto fixed in the latest release

**Comment by lindseydiloreto** [comment]
Woohoo! Thanks @jalendport, it looks fantastic! 👏
