### ISSUE TITLE
Channels are hidden based on app height

### ISSUE THREAD

**Issue by chasegiunta** [dennisfrank/decent-discord#8]
![image](https://user-images.githubusercontent.com/1377169/52918047-3a009a00-32b8-11e9-891b-a8cc16aeb998.png)
![image](https://user-images.githubusercontent.com/1377169/52918063-58ff2c00-32b8-11e9-9738-ef91c8fb6c1d.png)

**Comment by dennisfrank** [comment]
Thanks @chasegiunta. Yeah, I am aware of this issue. Discord does very strange things to the DOM. It removes and adds items dynamically on scroll position and hover. It’s difficult to overwrite with CSS. I am open for any idea!

**Comment by dennisfrank** [comment]
May be we should remove these changes to the channel items: https://github.com/dennisfrank/decent-discord/blob/master/src/components/channelbar.scss#L33-L46

What do you think @jalendport?

**Comment by jalendport** [comment]
I think that's best @dennisfrank - I tried something similar back before we made the repo / combined styles and I couldn't solve the DOM dynamic addition problem either. I think it's best to just leave it as Discord has it out of the box (for now at least).

**Comment by dennisfrank** [comment]
Fixed with [1.1.6](https://github.com/dennisfrank/decent-discord/releases/tag/1.1.6)
